import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Home.module.css'



export default function Home({data}) {
  return (
    <>
      <Head>
        <title>Tourists Website</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header> 
        <nav>
          <img />
          <a href='/'>Home</a>
          <a href='/tourist-sites'>Tourist Sites Page</a>
          <a href='/about-us'>About Us</a>
        </nav>
      </header>

      <main className={styles.main}>
        {data.map((t) => (
          <a key={t.id} href={`/tourist-sites/${t.id}`}>
            <Image width={200} height={200} alt={t.id} src={t.image}/>
            <h2>{t.title}</h2><p>{t.description}</p>
          </a>

        ))}
      </main>
    </>
  )
}

export async function getServerSideProps() {
  const { tourist_sites } = await import('/data/data.json');
  return {
    props: {
      data: tourist_sites,
    }
  }
}
