import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Home.module.css'



export default function Home({data}) {
  return (
    <>
      <Head>
        <title>Tourists Website</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header> 
        <nav>
          <img />
          <a href='/'>Home</a>
          <a href='/tourist-sites'>Tourist Sites Page</a>
          <a href='/about-us'>About Us</a>
        </nav>
      </header>

      <main className={styles.main}>
        {data.map((ev) => (
          <a key={ev.id} href={`/events/${ev.id}`}>
            <Image width={200} height={200} alt={ev.id} src={ev.image}/>
            <h2>{ev.title}</h2><p>{ev.description}</p>
          </a>

        ))}
         <a href="/">
            <img />
            <h2>Tourist Sites in Eastern Region</h2>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,
              molestiae quas vel sint commodi repudiandae consequuntur voluptatum laborum
              numquam blanditiis harum quisquam eius sed odit fugiat iusto fuga praesentium
             optio, eaque rerum! Provident similique accusantium nemo autem. Veritatis
             obcaecati tenetur iure eius earum ut molestias architecto voluptate aliquam
            nihil, eveniet aliquid culpa officia aut! Impedit sit sunt quaerat, odit,</p>
         </a>
         <a href="/">
            <img />
            <h2>Tourist Sites in Central Region</h2>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,
              molestiae quas vel sint commodi repudiandae consequuntur voluptatum laborum
              numquam blanditiis harum quisquam eius sed odit fugiat iusto fuga praesentium
             optio, eaque rerum! Provident similique accusantium nemo autem. Veritatis
             obcaecati tenetur iure eius earum ut molestias architecto voluptate aliquam
            nihil, eveniet aliquid culpa officia aut! Impedit sit sunt quaerat, odit,</p>
         </a>
         <a href="/">
            <img />
            <h2>Tourist Sites in Ashanti Region</h2>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,
              molestiae quas vel sint commodi repudiandae consequuntur voluptatum laborum
              numquam blanditiis harum quisquam eius sed odit fugiat iusto fuga praesentium
             optio, eaque rerum! Provident similique accusantium nemo autem. Veritatis
             obcaecati tenetur iure eius earum ut molestias architecto voluptate aliquam
            nihil, eveniet aliquid culpa officia aut! Impedit sit sunt quaerat, odit,</p>
         </a>
      </main>
    </>
  )
}

export async function getServerSideProps() {
  const { tourist_sites } = await import('/data/data.json');
  return {
    props: {
      data: tourist_sites,
    }
  }
}
